import re

with open("README.md", "r") as f:
    text = f.read()

# Let's fix the broken tables by capturing the blocks and transforming them
# This regex looks for lines starting with `|` followed by a newline, and captures the whole block
blocks = [
    # Table 1
    (r"\|\n Centralized Model \n\|\n NodeCommerce Model \n\|\n\|\n---\n\|\n---\n\|\n\|\n One central warehouse \n\|\n Thousands of local reseller nodes \n\|\n\|\n React to orders after they happen \n\|\n Pre-position stock based on forecasted demand \n\|\n\|\n Courier handles all last-mile \n\|\n Local reseller \n\*\nis\n\*\n the last mile — they're your neighbor \n\|\n\|\n Returns flow back to central hub \n\|\n Surplus flows sideways/locally via ACO, rarely needs reversal \n\|\n\|\n Stock sync via manual dashboards \n\|\n Atomic, transactional, product-code-based stock tracking \n\|\n\|\n \"Seller\" = anonymous online identity \n\|\n \"Local Reseller\" = a real shop you can walk to \n\|",
     "| Centralized Model | NodeCommerce Model |\n| --- | --- |\n| One central warehouse | Thousands of local reseller nodes |\n| React to orders after they happen | Pre-position stock based on forecasted demand |\n| Courier handles all last-mile | Local reseller *is* the last mile — they're your neighbor |\n| Returns flow back to central hub | Surplus flows sideways/locally via ACO, rarely needs reversal |\n| Stock sync via manual dashboards | Atomic, transactional, product-code-based stock tracking |\n| \"Seller\" = anonymous online identity | \"Local Reseller\" = a real shop you can walk to |"),
     
    # Table 2
    (r"\|\n Role \n\|\n Real-world equivalent \n\|\n Core responsibility \n\|\n\|\n---\n\|\n---\n\|\n---\n\|\n\|\n\*\*\nSeller\n\*\*\n\|\n Manufacturer / wholesaler / large producer \n\|\n Lists products \(AI-moderated via Ollama\), holds bulk stock \n\|\n\|\n\*\*\nLocal Reseller\n\*\*\n\|\n Neighborhood shop / kirana store \n\|\n Holds local stock, is the actual point of sale and delivery for buyers — \n\*\*\nthe trust layer\n\*\*\n\|\n\|\n\*\*\nUpazilla Reseller\n\*\*\n\|\n Sub-district distribution hub \n\|\n Aggregates local demand, receives Phase 1 stock, distributes to local resellers \n\|\n\|\n\*\*\nDistrict Reseller\n\*\*\n\|\n District-level depot \n\|\n Manages surplus, participates in Phase 2/3/4 ACO \n\|\n\|\n\*\*\nCity Reseller\n\*\*\n\|\n Metro distribution node \n\|\n Handles high-density urban routing for major cities \n\|\n\|\n\*\*\nBuyer\n\*\*\n\|\n End consumer \n\|\n Searches by GPS \+ product code, orders from the \n\*\nnearest\n\*\n stocked reseller \n\|\n\|\n\*\*\nSuperDashboard\n\*\*\n\|\n Operations control room \n\|\n Live Leaflet map of every node, pheromone trails, ACO trigger, conservation reports \n\|",
     "| Role | Real-world equivalent | Core responsibility |\n| --- | --- | --- |\n| **Seller** | Manufacturer / wholesaler / large producer | Lists products (AI-moderated via Ollama), holds bulk stock |\n| **Local Reseller** | Neighborhood shop / kirana store | Holds local stock, is the actual point of sale and delivery for buyers — **the trust layer** |\n| **Upazilla Reseller** | Sub-district distribution hub | Aggregates local demand, receives Phase 1 stock, distributes to local resellers |\n| **District Reseller** | District-level depot | Manages surplus, participates in Phase 2/3/4 ACO |\n| **City Reseller** | Metro distribution node | Handles high-density urban routing for major cities |\n| **Buyer** | End consumer | Searches by GPS + product code, orders from the *nearest* stocked reseller |\n| **SuperDashboard** | Operations control room | Live Leaflet map of every node, pheromone trails, ACO trigger, conservation reports |"),

    # Table 3
    (r"\|\n Layer \n\|\n Technology \n\|\n\|\n---\n\|\n---\n\|\n\|\n Frontend \n\|\n Next\.js 14 \(App Router\), TypeScript, Tailwind CSS \n\|\n\|\n Maps & Visualization \n\|\n Leaflet\.js, React Flow \(SuperDashboard \"God View\"\) \n\|\n\|\n Database \n\|\n PostgreSQL via Supabase, Prisma ORM \(20\+ models\) \n\|\n\|\n Auth \n\|\n Supabase Auth \(email/password, role-based\) \n\|\n\|\n AI — Product Moderation \n\|\n Ollama \(\n`qwen2\.5-coder:7b`\n\), local \"ISPAT\" gatekeeper \n\|\n\|\n AI — Demand Forecasting \n\|\n XGBoost \(Python/FastAPI\), LangChain \+ Claude Sonnet \n\|\n\|\n Routing Engine \n\|\n Custom TypeScript ACO engine \(\n`/lib/aco-multi-engine\.ts`\n\) \n\|\n\|\n Orchestration \n\|\n UiPath Maestro \(BPMN\), UiPath Orchestrator, Action Center \n\|\n\|\n Security \n\|\n HMAC-SHA256 signed QR codes, OAuth2 client credentials \(UiPath\) \n\|\n\|\n Deployment \n\|\n Vercel \(frontend\), Supabase \(backend\), FastAPI microservice \n\|",
     "| Layer | Technology |\n| --- | --- |\n| Frontend | Next.js 14 (App Router), TypeScript, Tailwind CSS |\n| Maps & Visualization | Leaflet.js, React Flow (SuperDashboard \"God View\") |\n| Database | PostgreSQL via Supabase, Prisma ORM (20+ models) |\n| Auth | Supabase Auth (email/password, role-based) |\n| AI — Product Moderation | Ollama (`qwen2.5-coder:7b`), local \"ISPAT\" gatekeeper |\n| AI — Demand Forecasting | XGBoost (Python/FastAPI), LangChain + Claude Sonnet |\n| Routing Engine | Custom TypeScript ACO engine (`/lib/aco-multi-engine.ts`) |\n| Orchestration | UiPath Maestro (BPMN), UiPath Orchestrator, Action Center |\n| Security | HMAC-SHA256 signed QR codes, OAuth2 client credentials (UiPath) |\n| Deployment | Vercel (frontend), Supabase (backend), FastAPI microservice |"),

    # Table 4
    (r"\|\n Endpoint \n\|\n Purpose \n\|\n\|\n---\n\|\n---\n\|\n\|\n`POST /api/aco/global-trigger`\n\|\n Run the full multi-product 4-phase ACO cycle \n\|\n\|\n`GET /api/aco/jobs`\n / \n`/api/aco/global-jobs/\[id\]`\n\|\n Inspect ACO job history and shipments \n\|\n\|\n`PATCH /api/aco/shipments/\[id\]/approve`\n\|\n Approve/reject a Phase 3 inter-district shipment \n\|\n\|\n`GET /api/aco/pheromones`\n\|\n Pheromone heatmap data for the SuperDashboard \n\|\n\|\n`POST /api/aco/negotiate`\n / \n`PATCH /api/aco/negotiate/\[id\]`\n\|\n Seller price negotiation for ACO stock \n\|\n\|\n`GET /api/demand/upazilla`\n / \n`GET /api/demand/district`\n\|\n Demand entry and rollup \n\|\n\|\n`POST /api/agent/demand-pulse`\n / \n`POST /api/agent/demand-apply`\n\|\n Autonomous demand agent collection & write-back \n\|\n\|\n`GET /api/delivery/search`\n\|\n Location \+ product-code based reseller search \n\|\n\|\n`POST /api/delivery/orders`\n / \n`\.\.\./qr-confirm`\n\|\n Place and confirm last-mile delivery orders \n\|\n\|\n`POST /api/uipath/shipment-action`\n\|\n UiPath Action Center callback for Phase 3 \n\|\n\|\n`GET /api/aco/verify-conservation`\n\|\n Run the 5-invariant conservation check \n\|\n\|\n`GET /api/superdashboard/nodes`\n\|\n All node positions/stock for the live map \n\|",
     "| Endpoint | Purpose |\n| --- | --- |\n| `POST /api/aco/global-trigger` | Run the full multi-product 4-phase ACO cycle |\n| `GET /api/aco/jobs` / `/api/aco/global-jobs/[id]` | Inspect ACO job history and shipments |\n| `PATCH /api/aco/shipments/[id]/approve` | Approve/reject a Phase 3 inter-district shipment |\n| `GET /api/aco/pheromones` | Pheromone heatmap data for the SuperDashboard |\n| `POST /api/aco/negotiate` / `PATCH /api/aco/negotiate/[id]` | Seller price negotiation for ACO stock |\n| `GET /api/demand/upazilla` / `GET /api/demand/district` | Demand entry and rollup |\n| `POST /api/agent/demand-pulse` / `POST /api/agent/demand-apply` | Autonomous demand agent collection & write-back |\n| `GET /api/delivery/search` | Location + product-code based reseller search |\n| `POST /api/delivery/orders` / `.../qr-confirm` | Place and confirm last-mile delivery orders |\n| `POST /api/uipath/shipment-action` | UiPath Action Center callback for Phase 3 |\n| `GET /api/aco/verify-conservation` | Run the 5-invariant conservation check |\n| `GET /api/superdashboard/nodes` | All node positions/stock for the live map |"),

    # Table 5
    (r"\|\n Judging Criteria \n\|\n Where NodeCommerce delivers \n\|\n\|\n---\n\|\n---\n\|\n\|\n\*\*\nInnovation \(20%\)\n\*\*\n\|\n Pre-emptive \(not reactive\) routing; Ant Colony Optimization applied to real-world multi-tier logistics; multi-product truck bundling \n\|\n\|\n\*\*\nTechnical Execution \(20%\)\n\*\*\n\|\n 20\+ Prisma models, 48\+ API routes, custom ACO math engine, mathematically-verified conservation, XGBoost \+ LangChain hybrid forecasting \n\|\n\|\n\*\*\nBusiness Model \(20%\)\n\*\*\n\|\n Three revenue streams \(platform SaaS, transaction commission, demand-intelligence API\), modular district-by-district rollout, South Asia expansion path \n\|\n\|\n\*\*\nReal-World Impact \(20%\)\n\*\*\n\|\n Addresses a structurally lossy market \(see \n\[\nThe Problem\n\]\(\n#-the-problem\n\)\n\); Bangla-first UX; human-in-the-loop AI by design \n\|\n\|\n\*\*\nScalability \+ NRB \(10%\)\n\*\*\n\|\n Configuration-driven district expansion \(no code changes\); cloud-native \(Vercel \+ Supabase\); NRB diaspora investment pathway \n\|\n\|\n\*\*\nPresentation \(10%\)\n\*\*\n\|\n Live SuperDashboard map demo, real-time truck animation, end-to-end buyer-to-delivery walkthrough \n\|",
     "| Judging Criteria | Where NodeCommerce delivers |\n| --- | --- |\n| **Innovation (20%)** | Pre-emptive (not reactive) routing; Ant Colony Optimization applied to real-world multi-tier logistics; multi-product truck bundling |\n| **Technical Execution (20%)** | 20+ Prisma models, 48+ API routes, custom ACO math engine, mathematically-verified conservation, XGBoost + LangChain hybrid forecasting |\n| **Business Model (20%)** | Three revenue streams (platform SaaS, transaction commission, demand-intelligence API), modular district-by-district rollout, South Asia expansion path |\n| **Real-World Impact (20%)** | Addresses a structurally lossy market (see [The Problem](#-the-problem)); Bangla-first UX; human-in-the-loop AI by design |\n| **Scalability + NRB (10%)** | Configuration-driven district expansion (no code changes); cloud-native (Vercel + Supabase); NRB diaspora investment pathway |\n| **Presentation (10%)** | Live SuperDashboard map demo, real-time truck animation, end-to-end buyer-to-delivery walkthrough |")
]

for pat, rep in blocks:
    text = re.sub(pat, rep, text)

with open("README.md", "w") as f:
    f.write(text)

print("Done")
