// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import * as fs from "fs";
import { defineConfig } from "prisma/config";

// Load .env.local overrides (DIRECT_URL lives here)
try {
  const localEnv = fs.readFileSync(".env.local", "utf-8");
  for (const line of localEnv.split("\n")) {
    const m = line.match(/^([^#=]+)=(.*)$/);
    if (m && !process.env[m[1].trim()]) {
      process.env[m[1].trim()] = m[2].trim().replace(/^["']|["']$/g, "");
    }
  }
} catch { /* .env.local may not exist */ }

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL (non-pooled port 5432) for migrations/push operations.
    // Fall back to DATABASE_URL for regular queries.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
