import { inngest } from "./client";
import { generateRandomDemand } from "@/lib/agents/demand";
import { buildForecastingGraph } from "@/lib/agents/graph";
import { prisma } from "@/lib/prisma";

export const runIntelligencePipeline = inngest.createFunction(
  { 
    id: "run-intelligence-pipeline",
    triggers: [{ event: "ai/trigger.intelligence" }]
  },
  async ({ event, step }) => {
    // 1. Generate Demand
    const demandResult = await step.run("generate-demand", async () => {
      return await generateRandomDemand();
    });

    // 2. Fetch State
    const { upazillaStocks, demands } = await step.run("fetch-state", async () => {
      const upazillaStocks = await prisma.upazillaAvailableStock.findMany({
        include: { upazillaReseller: true }
      });
      const demands = await prisma.upazillaDemand.findMany({
        where: { status: 'pending' },
        include: { upazillaReseller: true }
      });
      return { upazillaStocks, demands };
    });

    // 3. Execute LangGraph
    const finalState = await step.run("execute-langgraph", async () => {
      const initialState = {
        stockSnapshot: upazillaStocks,
        demands: demands,
        criticalAlerts: [],
        forecasts: [],
        reorderActions: []
      };
      const graph = buildForecastingGraph();
      return await graph.invoke(initialState);
    });

    // 4. Apply Database Mutations
    const executedOrders = await step.run("apply-actions", async () => {
      const createdIds = [];
      if (finalState.restockRecommendations && finalState.restockRecommendations.length > 0) {
        const defaultSeller = await prisma.profile.findFirst({ 
          where: { role: 'seller' }, 
          include: { products: true } 
        });
        
        if (defaultSeller && defaultSeller.products.length > 0) {
          for (const rec of finalState.restockRecommendations) {
             const matchingProduct = defaultSeller.products.find(p => p.productCode === rec.productCode) || defaultSeller.products[0];
             const upazilla = upazillaStocks.length > 0 ? upazillaStocks[Math.floor(Math.random() * upazillaStocks.length)].upazillaResellerId : null;
             
             if (upazilla) {
               const order = await prisma.stockOrderNegotiation.create({
                  data: {
                    upazillaResellerId: upazilla,
                    sellerId: defaultSeller.id,
                    sellerProductId: matchingProduct.id,
                    productCode: matchingProduct.productCode,
                    productName: matchingProduct.customName || "AI Auto Restock",
                    requestedQuantity: rec.quantityKg || 100,
                    originalPrice: matchingProduct.price,
                    negotiatedPrice: matchingProduct.price,
                    status: 'pending',
                    sellerNote: `Auto-generated by REORDER Agent. Priority: ${rec.priority}`
                  }
               });
               createdIds.push(order.id);
             }
          }
        }
      }
      return createdIds;
    });

    return {
      success: true,
      demandsGenerated: demandResult.generated,
      alerts: finalState.criticalAlerts.length,
      actions: executedOrders.length
    };
  }
);
